[project]
name = "buque"
version = "0.1.0"
description = "Buque PDF bookmark tagging tool (M1)"
readme = "README.md"
authors = [
    { name = "loheagn", email = "loheagn@icloud.com" }
]
requires-python = ">=3.11"
dependencies = [
    "pydantic>=2.12.5",
    "pymupdf>=1.27.2",
    "pyyaml>=6.0.3",
    "typer>=0.24.1",
]

[project.scripts]
buque = "buque.cli:app"

[build-system]
requires = ["uv_build>=0.9.17,<0.10.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = ""
module-name = "buque"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
